url: http://rudylattae.github.com/jasmine-species
title: Jasmine-Species 
description: Extended BDD grammar and styled reporting for Jasmine
keywords: Jasmine, jasmine-species, javascript, bdd, feature, story, given, when, then, bdd grammar, bdd style
author: Rudy Lattae
email: rudylattae@gmail.com
copyright: &copy 2010 - Rudy Lattae
